apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.registration.serviceAccountName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: kubecraft
    component: registration

