apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.registration.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: kubecraft
    component: registration
spec:
  type: {{ .Values.registration.service.type }}
  selector:
    app: kubecraft
    component: registration
  ports:
    - port: {{ .Values.registration.service.port }}
      targetPort: {{ .Values.registration.service.targetPort }}
      nodePort: {{ .Values.registration.service.nodePort }}
      protocol: TCP

